version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      python-development:
        dependency-type: development
      python-verification:
        patterns:
          - "http-message-signatures"
          - "cryptography"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
