documentation:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md", "docs/**"]

github_actions:
  - changed-files:
      - any-glob-to-any-file: [".github/workflows/**", ".github/dependabot.yml", ".github/labeler.yml"]

dependencies:
  - changed-files:
      - any-glob-to-any-file: ["pyproject.toml", "**/*lock*"]

enhancement:
  - head-branch: ["^feat/"]

bug:
  - head-branch: ["^fix/"]
